ACTIVITY = {
    ('img/activity/basketball.png', 1),
    ('img/activity/bicycle.png', 2),
    ('img/activity/bowling.png', 3),
    ('img/activity/dancing.png', 4),
    ('img/activity/football.png', 5),
    ('img/activity/horse-riding.png', 6),
    ('img/activity/lifting.png', 7),
    ('img/activity/motocross.png', 8),
    ('img/activity/ping-pong.png', 9),
    ('img/activity/pullups.png', 10),
    ('img/activity/rolls.png', 11),
    ('img/activity/run.png', 12),
    ('img/activity/skate.png', 13),
    ('img/activity/skiing.png', 14),
    ('img/activity/snowboard.png', 15),
    ('img/activity/tennis.png', 16),
    ('img/activity/trekking.png', 17),
    ('img/activity/volleyball.png', 18),
    ('img/activity/walking.png', 19),
    ('img/activity/yoga.png', 20),
}
