# Generated by Django 3.1.4 on 2021-01-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/users/%Y/%m/%d')),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=150, null=True)),
                ('inst', models.CharField(blank=True, max_length=150, null=True)),
                ('vk', models.CharField(blank=True, max_length=150, null=True)),
                ('fb', models.CharField(blank=True, max_length=150, null=True)),
                ('act', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
