# Generated by Django 3.1.4 on 2021-03-07 09:58

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/users/%Y/%m/%d')),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=150, null=True)),
                ('inst', models.CharField(blank=True, max_length=150, null=True)),
                ('vk', models.CharField(blank=True, max_length=150, null=True)),
                ('fb', models.CharField(blank=True, max_length=150, null=True)),
                ('act', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'basketball'), ('2', 'bicycle'), ('3', 'bowling'), ('4', 'dancing'), ('5', 'football'), ('6', 'horse-riding'), ('7', 'lifting'), ('8', 'motocross'), ('9', 'ping-pong'), ('10', 'pullups'), ('11', 'rolls'), ('12', 'run'), ('13', 'skate'), ('14', 'skiing'), ('15', 'snowboard'), ('16', 'tennis'), ('17', 'trekking'), ('18', 'volleyball'), ('19', 'walking'), ('20', 'yoga')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
