# Generated by Django 3.1.4 on 2021-02-09 18:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='act',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Basketball'), ('2', 'Football')], max_length=3),
        ),
    ]
