# Generated by Django 3.1.4 on 2021-02-09 19:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20210209_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='act',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'basketball'), ('2', 'bicycle'), ('3', 'bowling'), ('4', 'dancing'), ('5', 'football'), ('6', 'horse-riding'), ('7', 'lifting'), ('8', 'motocross'), ('9', 'ping-pong'), ('10', 'pullups'), ('11', 'rolls'), ('12', 'run'), ('13', 'skate'), ('14', 'skiing'), ('15', 'snowboard'), ('16', 'tennis'), ('17', 'trekking'), ('18', 'volleyball'), ('19', 'walking'), ('20', 'yoga')], max_length=50),
        ),
    ]
