# Generated by Django 3.1.4 on 2021-01-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20201229_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
