# Generated by Django 3.1.4 on 2021-04-04 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Katka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=150)),
                ('date', models.DateField(max_length=150)),
                ('time', models.TimeField(max_length=150)),
                ('descr', models.CharField(max_length=350)),
                ('katka_act', multiselectfield.db.fields.MultiSelectField(choices=[('img/activity/tennis.png', 16), ('img/activity/motocross.png', 8), ('img/activity/dancing.png', 4), ('img/activity/yoga.png', 20), ('img/activity/lifting.png', 7), ('img/activity/ping-pong.png', 9), ('img/activity/football.png', 5), ('img/activity/horse-riding.png', 6), ('img/activity/run.png', 12), ('img/activity/rolls.png', 11), ('img/activity/basketball.png', 1), ('img/activity/volleyball.png', 18), ('img/activity/pullups.png', 10), ('img/activity/snowboard.png', 15), ('img/activity/trekking.png', 17), ('img/activity/bowling.png', 3), ('img/activity/skate.png', 13), ('img/activity/walking.png', 19), ('img/activity/bicycle.png', 2), ('img/activity/skiing.png', 14)], max_length=505)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Катка',
                'verbose_name_plural': 'Все события Катка',
                'ordering': ['-id'],
            },
        ),
    ]
