# Generated by Django 3.1.4 on 2021-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=150)),
                ('date', models.DateField(max_length=150)),
                ('time', models.TimeField(max_length=150)),
                ('descr', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Катка',
                'verbose_name_plural': 'Все события Катка',
            },
        ),
    ]
