# Generated by Django 3.1.4 on 2021-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katka',
            name='members',
            field=models.ManyToManyField(related_name='profile_set', to='profile.Profile'),
        ),
    ]
