# Generated by Django 3.1.4 on 2021-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katka',
            name='members',
            field=models.ManyToManyField(to='profile.Profile'),
        ),
    ]
