# Generated by Django 3.1.4 on 2021-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('main', '0002_katka_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katka',
            name='members',
            field=models.ManyToManyField(related_name='profile_set', to='profile.Profile'),
        ),
    ]
