# Generated by Django 3.1.4 on 2021-01-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210104_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='katka',
            old_name='k_descriptions',
            new_name='descr',
        ),
    ]
