# Generated by Django 3.1.4 on 2021-03-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210328_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katka',
            options={'ordering': ['-id'], 'verbose_name': 'Катка', 'verbose_name_plural': 'Все события Катка'},
        ),
    ]
