# Generated by Django 3.2 on 2021-06-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0030_alter_profile_act'),
        ('katkamessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katkamessage',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile', verbose_name='Профиль автора'),
        ),
    ]
