# Generated by Django 3.2 on 2021-06-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0031_alter_profile_act'),
        ('katkamessages', '0002_katkamessage_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katkamessage',
            name='author_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile', verbose_name='Профиль автора'),
        ),
    ]
