# Generated by Django 3.2 on 2021-06-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katkamessages', '0003_alter_katkamessage_author_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katkamessage',
            name='author_profile',
        ),
    ]
